services:
  # node:
  #   build:
  #       context: .
  #   container_name: node
  #   tty: true
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./:/usr/src/app
  #   depends_on:
  #     mysql:
  #       condition: service_healthy

  node-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: node-prod
    depends_on:
      mysql:
        condition: service_healthy
    
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "3001:80"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest
    container_name: mysql-node
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node
    healthcheck:
      test: mysqladmin ping
      interval: 5s
      timeout: 3s
      retries: 3

